# Generated by Django 3.2.5 on 2022-04-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Pending', 'Pending'), ('Out of delivery', 'Out of delivery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('shoes', 'shoes'), ('Clothes', 'Clothes'), ('Kitchen', 'Kitchen')], max_length=50),
        ),
    ]
