# Generated by Django 3.2.5 on 2022-04-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
    ]
